### ISSUE TITLE
No issues, wanted general information.

### ISSUE THREAD

**Issue by mithilesh-parmar** [hadyk77/HChat#1]
I like the architecture you're using here. Can you give me details on
 - What architecture is this? Is this Uncle bob's clean architecture?
 - Can you point me in the direction for the resources from where I can read more about the architecture and the approach you are using?

**Comment by hadyk77** [comment]
this architcture called DDD (Domain driven design )
here list of tutorials you can follow to achieve this
https://resocoder.com/2020/03/09/flutter-firebase-ddd-course-1-domain-driven-design-principles/

‫في الاثنين، 11 مايو 2020 في 3:08 م تمت كتابة ما يلي بواسطة ‪Mithilesh
Parmar‬‏ <‪notifications@github.com‬‏>:‬

**Comment by mithilesh-parmar** [comment]
> this architcture called DDD (Domain driven design ) here list of tutorials you can follow to achieve this https://resocoder.com/2020/03/09/flutter-firebase-ddd-course-1-domain-driven-design-principles/ ‫في الاثنين، 11 مايو 2020 في 3:08 م تمت كتابة ما يلي بواسطة ‪Mithilesh Parmar‬‏ <‪notifications@github.com‬‏>:‬
> […](#)

Thanks
